const { DataTypes } = require('sequelize');
const sequelize = require('../config/mysql');

const Data = sequelize.define('Data', {
    id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true
    },
    OBJECTID: DataTypes.INTEGER,
    X: DataTypes.DECIMAL(10, 6),
    Y: DataTypes.DECIMAL(10, 6),
    FAC_ID: DataTypes.STRING,
    POINT_ID: DataTypes.INTEGER,
    NEAR_ID_1: DataTypes.INTEGER,
    NEAR_ID_2: DataTypes.INTEGER,
    NEAR_ID_3: DataTypes.INTEGER,
    AIR_CODE: DataTypes.STRING,
    AIR_CODE2: DataTypes.STRING,
    AMTRAKCODE: DataTypes.STRING,
    FERRY_CODE: DataTypes.STRING,
    RAIL_ID: DataTypes.STRING,
    BIKE_ID: DataTypes.STRING,
    DATE_UPDTE: DataTypes.DATE,
    ADDRESS: DataTypes.STRING,
    CITY: DataTypes.STRING,
    STATE: DataTypes.STRING,
    ZIPCODE: DataTypes.STRING,
    METRO_AREA: DataTypes.STRING,
    FAC_NAME: DataTypes.STRING,
    LONGITUDE: DataTypes.DECIMAL(10, 6),
    LATITUDE: DataTypes.DECIMAL(10, 6),
    POINT_LON: DataTypes.DECIMAL(10, 6),
    POINT_LAT: DataTypes.DECIMAL(10, 6),
    FAC_TYPE: DataTypes.STRING,
    FERRY_T: DataTypes.BOOLEAN,
    FERRY_I: DataTypes.BOOLEAN,
    BUS_T: DataTypes.BOOLEAN,
    BUS_I: DataTypes.BOOLEAN,
    BUS_CODE_S: DataTypes.STRING,
    BUS_SUPP: DataTypes.BOOLEAN,
    RAIL_I: DataTypes.BOOLEAN,
    RAIL_C: DataTypes.STRING,
    RAIL_H: DataTypes.BOOLEAN,
    RAIL_LIGHT: DataTypes.BOOLEAN,
    AIR_SERVE: DataTypes.BOOLEAN,
    BIKE_SHARE: DataTypes.BOOLEAN,
    BIKE_SYS_ID: DataTypes.STRING,
    BIKE_SYS: DataTypes.STRING,
    WEBSITE: DataTypes.STRING,
    NOTES: DataTypes.TEXT,
    SOURCE: DataTypes.STRING,
    I_SERVICE: DataTypes.BOOLEAN,
    T_SERVICE: DataTypes.BOOLEAN,
    CBSA_CODE: DataTypes.INTEGER,
    CBSA_TYPE: DataTypes.INTEGER,
    MODES_SERV: DataTypes.INTEGER,
    MODE_BUS: DataTypes.BOOLEAN,
    MODE_AIR: DataTypes.BOOLEAN,
    MODE_RAIL: DataTypes.BOOLEAN,
    MODE_FERRY: DataTypes.BOOLEAN,
    MODE_BIKE: DataTypes.BOOLEAN,
    x2: DataTypes.DECIMAL(10, 6),
    y2: DataTypes.DECIMAL(10, 6),
}, {
    timestamps: true,
    tableName: 'data',
});

module.exports = Data;
